import { colorAnim } from './Data/animalsData.ts';
colorAnim.forEach(anim => console.log(anim.name))

const futureData = [
    {
        id: 21,
        name: "Axolotl",
        defaultMode: "light",
        categories: ["health", "blog", "portfolio"],
        sites: ["journal-app", "therapy-booking", "wellness-landing"],
        tagline: "Soft on the eyes. Tough on bugs.",
        font: { main: "Quicksand", body: "Nunito Sans" },
    },
    {
        id: 22,
        name: "Narwhal",
        defaultMode: "dark",
        categories: ["fintech", "saas", "ecommerce"],
        sites: ["crypto-dashboard", "banking-app", "invoice-app"],
        tagline: "Sharp numbers. Cold precision.",
        font: { main: "Space Grotesk", body: "IBM Plex Sans" },
    },
    {
        id: 23,
        name: "Chameleon",
        defaultMode: "light",
        categories: ["agency", "portfolio", "saas"],
        sites: ["portfolio-site", "design-tool", "brand-site"],
        tagline: "Adapts to every brand. Never blends in.",
        font: { main: "Bricolage Grotesque", body: "Inter" },
    },
    {
        id: 24,
        name: "Hornbill",
        defaultMode: "light",
        categories: ["travel", "ecommerce", "blog"],
        sites: ["booking-app", "hotel-site", "travel-blog"],
        tagline: "Loud colors. Smooth landings.",
        font: { main: "Fraunces", body: "Work Sans" },
    },
    {
        id: 25,
        name: "Quokka",
        defaultMode: "light",
        categories: ["community", "saas", "blog"],
        sites: ["community-app", "forum-site", "social-landing"],
        tagline: "Friendly by default.",
        font: { main: "Outfit", body: "DM Sans" },
    },
    {
        id: 26,
        name: "Komodo Dragon",
        defaultMode: "dark",
        categories: ["ecommerce", "fitness", "blog"],
        sites: ["gear-shop", "fitness-app", "outdoor-blog"],
        tagline: "Built for rough terrain.",
        font: { main: "Sora", body: "Manrope" },
    },
    {
        id: 27,
        name: "Cuttlefish",
        defaultMode: "dark",
        categories: ["portfolio", "agency", "blog"],
        sites: ["photo-portfolio", "studio-site", "gallery-app"],
        tagline: "Colors that shift with light.",
        font: { main: "Newsreader", body: "Albert Sans" },
    },
    {
        id: 28,
        name: "Hammerhead Shark",
        defaultMode: "dark",
        categories: ["saas", "security", "fintech"],
        sites: ["security-dashboard", "b2b-landing", "admin-dashboard"],
        tagline: "Sees the threat before you do.",
        font: { main: "Plus Jakarta Sans", body: "IBM Plex Sans" },
    },
    {
        id: 29,
        name: "Honey Badger",
        defaultMode: "dark",
        categories: ["gaming", "saas", "blog"],
        sites: ["esports-site", "gaming-dashboard", "streaming-app"],
        tagline: "Doesn't care. Looks great doing it.",
        font: { main: "Red Hat Display", body: "Inter" },
    },
    {
        id: 30,
        name: "Snowy Owl",
        defaultMode: "light",
        categories: ["productivity", "saas", "portfolio"],
        sites: ["notes-app", "productivity-dashboard", "minimal-landing"],
        tagline: "Quiet UI. Sharp focus.",
        font: { main: "Lexend", body: "Work Sans" },
    },
    {
        id: 31,
        name: "Vampire Squid",
        defaultMode: "dark",
        categories: ["music", "ecommerce", "blog"],
        sites: ["event-site", "music-label", "ticket-app"],
        tagline: "Deep red. Deeper bass.",
        font: { main: "Schibsted Grotesk", body: "Albert Sans" },
    },
    {
        id: 32,
        name: "Tarsier",
        defaultMode: "light",
        categories: ["education", "saas", "blog"],
        sites: ["kids-app", "elearning-portal", "edu-landing"],
        tagline: "Wide-eyed wonder, structured lessons.",
        font: { main: "Quicksand", body: "Nunito Sans" },
    },
    {
        id: 33,
        name: "Capybara",
        defaultMode: "light",
        categories: ["blog", "health", "portfolio"],
        sites: ["personal-site", "journal-blog", "slow-living-site"],
        tagline: "No rush. Just warmth.",
        font: { main: "Fraunces", body: "Nunito Sans" },
    },
    {
        id: 34,
        name: "Hyena",
        defaultMode: "light",
        categories: ["news", "blog", "saas"],
        sites: ["news-site", "media-dashboard", "magazine-site"],
        tagline: "Loud headlines. Tight grid.",
        font: { main: "Newsreader", body: "Work Sans" },
    },
    {
        id: 35,
        name: "Anglerfish",
        defaultMode: "dark",
        categories: ["gaming", "music", "saas"],
        sites: ["streaming-app", "gaming-landing", "dark-dashboard"],
        tagline: "Lights up in the dark.",
        font: { main: "Space Grotesk", body: "Manrope" },
    },
    {
        id: 36,
        name: "Platypus",
        defaultMode: "light",
        categories: ["saas", "portfolio", "blog"],
        sites: ["dev-tool", "startup-landing", "docs-site"],
        tagline: "Weird combo. Somehow works.",
        font: { main: "Outfit", body: "IBM Plex Sans" },
    },
    {
        id: 37,
        name: "Mandrill",
        defaultMode: "light",
        categories: ["marketing", "agency", "ecommerce"],
        sites: ["campaign-site", "agency-landing", "brand-store"],
        tagline: "Impossible to ignore.",
        font: { main: "Bricolage Grotesque", body: "DM Sans" },
    },
    {
        id: 38,
        name: "Glass Frog",
        defaultMode: "light",
        categories: ["portfolio", "saas", "blog"],
        sites: ["minimal-portfolio", "design-system-site", "docs-site"],
        tagline: "Nothing to hide.",
        font: { main: "Lexend", body: "Inter" },
    },
    {
        id: 39,
        name: "Electric Eel",
        defaultMode: "dark",
        categories: ["saas", "fintech", "ecommerce"],
        sites: ["energy-dashboard", "utility-app", "smart-home-site"],
        tagline: "Powered up. Plugged in.",
        font: { main: "Sora", body: "Manrope" },
    },
    {
        id: 40,
        name: "Pangolin",
        defaultMode: "dark",
        categories: ["fintech", "saas", "security"],
        sites: ["insurance-site", "security-app", "admin-dashboard"],
        tagline: "Armored by default.",
        font: { main: "Plus Jakarta Sans", body: "Work Sans" },
    },
];